language: python
python:
  - "3.4"
sudo: false
# command to install dependencies
install: pip install -r requirements.txt
# command to prepare for tests
before_script:
# Uncomment this to get the full corpus (required to train/test on it):
#  - curl -O http://www.cs.huji.ac.il/~danielh/ucca/ucca_corpus_pickle.tgz
#  - mkdir pickle
#  - tar xvzf ucca_corpus_pickle.tgz -C pickle
#  - python scripts/split.py pickle
  - python setup.py install
  - python -m nltk.downloader averaged_perceptron_tagger punkt
# command to run tests
script:
  - python -m unittest discover -v
  - python parser/parser.py -I 10 -t doc/toy.xml -d doc/toy.xml -m model_toy
  - python parser/parser.py doc/toy.xml -m model_toy
  - python parser/parser.py -I 10 -t doc/toy.xml -d doc/toy.xml -sm model_toy_sentences
  - python parser/parser.py doc/toy.xml -sm model_toy_sentences
  - python parser/parser.py -I 10 -t doc/toy.xml -d doc/toy.xml -am model_toy_paragraphs
  - python parser/parser.py doc/toy.xml -sm model_toy_paragraphs
# Uncomment this to train on the full training set (takes ~30 minutes):
#  - python parser/parser.py -t pickle/train -d pickle/dev -bm model
# Uncomment this to test on the full test set:
#  - python parser/parser.py pickle/test -bm model