cache: apt
sudo: false
language: python
python:
  - "3.4.4"
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
    - libhdf5-serial-dev
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy
  - pip install pytest-pep8
  - pip install -r requirements.txt
  - python -m nltk.downloader averaged_perceptron_tagger punkt
  - python setup.py install
before_script:
  - mkdir pickle word_vectors
  - curl -L http://www.cs.huji.ac.il/~danielh/ucca/ucca_corpus_pickle.tgz | tar xz -C pickle
  - curl -L http://www.cs.huji.ac.il/~danielh/ucca/w2v.tgz | tar xz -C word_vectors
  - python scripts/split_corpus.py -l pickle
env:
  - TEST_SUITE=unit
  - TEST_SUITE=sparse
  - TEST_SUITE=dense
  - TEST_SUITE=nn
  - TEST_SUITE=tune
  - TEST_SUITE=convert
script:
  - ci/test.sh
